/**
* CybeCube Gate
* This is the api for the cybecube gate.  The cybecube gate is an way to access programmatically cybecube's virtual assistents.
*
* OpenAPI spec version: 1.0.0
* Contact: info@cybecube.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cybecube.academy.registry

import com.cybecube.academy.registry.model.Course
import com.fasterxml.jackson.annotation.JsonBackReference
import javax.persistence.*

/**
 * 
 * @param id 
 * @param title 
 * @param courses
 */
@Entity
@Table(name = "academy")
data class Academy (

    @Id @GeneratedValue(strategy= GenerationType.AUTO)
    val id: Long? = null,

    @Basic(optional = false) @Column(name = "title", nullable = false, length = 128)
    val title: String? = null,

    @OneToMany(cascade = arrayOf(CascadeType.ALL),mappedBy = "course",fetch = FetchType.LAZY)
    val courses: Set<Course>? = null

)