/**
* CybeCube Gate
* This is the api for the cybecube gate.  The cybecube gate is an way to access programmatically cybecube's virtual assistents.
*
* OpenAPI spec version: 1.0.0
* Contact: info@cybecube.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cybecube.academy.registry

import com.cybecube.academy.registry.model.Course

/**
 * 
 * @param id 
 * @param title 
 * @param course 
 */
data class Academy (
    val id: kotlin.Long? = null,
    val title: kotlin.String? = null,
    val course: kotlin.Array<Course>? = null
) {

}

