/**
* CybeCube Gate
* This is the api for the cybecube gate.  The cybecube gate is an way to access programmatically cybecube's virtual assistents.
*
* OpenAPI spec version: 1.0.0
* Contact: info@cybecube.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cybecube.academy.registry.model

import com.cybecube.academy.registry.model.Location
import com.cybecube.academy.registry.model.State
import javax.persistence.Entity

/**
 * 
 * @param id 
 * @param title 
 * @param name 
 * @param state 
 * @param location 
 * @param date_of_birth 
 * @param gender 
 * @param &#x60;class&#x60; 
 * @param alive 
 */
@Entity
data class Assistant (
    val id: kotlin.Long? = null,
    val title: kotlin.String? = null,
    val name: kotlin.String? = null,
    val state: State? = null,
    val location: Location? = null,
    val date_of_birth: kotlin.String? = null,
    val gender: kotlin.String? = null,
    val `class`: kotlin.String? = null,
    val alive: kotlin.Boolean? = null
) {

}

