/**
* CybeCube Gate
* This is the api for the cybecube gate.  The cybecube gate is an way to access programmatically cybecube's virtual assistents.
*
* OpenAPI spec version: 1.0.0
* Contact: info@cybecube.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cybecube.academy.registry.model

import com.cybecube.academy.registry.model.Assistant

/**
 * 
 * @param id 
 * @param title 
 * @param initDate 
 * @param status Course Status
 * @param worker 
 * @param complete 
 */
data class Course (
    val id: kotlin.Long? = null,
    val title: kotlin.String? = null,
    val initDate: java.time.LocalDateTime? = null,
    /* Course Status */
    val status: Course.Status? = null,
    val worker: kotlin.Array<Assistant>? = null,
    val complete: kotlin.Boolean? = null
) {

    /**
    * Course Status
    * Values: running,finished,preparing
    */
    enum class Status(val value: kotlin.Any){
        running("running"),
        finished("finished"),
        preparing("preparing");
    }

}

