/**
* CybeCube Gate
* This is the api for the cybecube gate.  The cybecube gate is an way to access programmatically cybecube's virtual assistents.
*
* OpenAPI spec version: 1.0.0
* Contact: info@cybecube.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cybecube.academy.registry.model

import com.cybecube.academy.registry.model.Assistant
import javax.persistence.*

/**
 * 
 * @param id 
 * @param title 
 * @param initDate 
 * @param status Course Status
 * @param worker 
 * @param complete 
 */
@Entity
@Table(name = "course")
data class Course (

    @Id @GeneratedValue(strategy= GenerationType.AUTO)
    val id: Long? = null,

    @Basic(optional = false) @Column(name = "title", nullable = false, length = 128)
    val title: String? = null,

    @Basic(optional = false) @Column(name = "initDate", nullable = false, length = 10)
    val initDate: String? = null,

        /* Course Status */
    @Basic(optional = false) @Column(name = "status", nullable = false, length = 30)
    val status: Status? = null,

    @OneToMany(cascade = [CascadeType.ALL], mappedBy = "assistant", fetch = FetchType.LAZY)
    val assistant: Set<Assistant>? = null,

    @Basic(optional = false) @Column(name = "complete", nullable = false)
    val complete: Boolean? = null
) {

    /**
    * Course Status
    * Values: running,finished,preparing
    */
    enum class Status(val value: kotlin.Any){
        running("running"),
        finished("finished"),
        preparing("preparing");
    }

}

