/**
* CybeCube Gate
* This is the api for the cybecube gate.  The cybecube gate is an way to access programmatically cybecube's virtual assistents.
*
* OpenAPI spec version: 1.0.0
* Contact: info@cybecube.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cybecube.academy.registry.model

import javax.persistence.*


/**
 * 
 * @param id 
 * @param address Logical address of the assistant
 * @param va_host Physical server/host/ip address
 * @param va_node Logical address linked to host
 * @param va_ports Linked list of ports, as string
 * @param cloud_address Location info linked to cloud services (AWS,Azure,Google)
 */
@Entity
@Table(name = "location")
data class Location (
        @Id @GeneratedValue(strategy= GenerationType.AUTO)
        val id: Long? = null,

        /* Logical address of the assistant */
        @Basic(optional = false) @Column(name = "address", nullable = false, length = 30)
        val address: String? = null,

        /* Physical server/host/ip address */
        @Basic(optional = false) @Column(name = "va_host", nullable = false, length = 30)
        val va_host: String? = null,

        /* Logical address linked to host */
        @Basic(optional = false) @Column(name = "va_node", nullable = false, length = 30)
        val va_node: String? = null,

        /* Linked list of ports, as string */
        @Basic(optional = false) @Column(name = "va_ports", nullable = false, length = 30)
        val va_ports: String? = null,

        /* Location info linked to cloud services (AWS,Azure,Google) */
        @Basic(optional = false) @Column(name = "cloud_address", nullable = false, length = 10)
        val cloud_address: String? = null
) {

}

