/**
* CybeCube Gate
* This is the api for the cybecube gate.  The cybecube gate is an way to access programmatically cybecube's virtual assistents.
*
* OpenAPI spec version: 1.0.0
* Contact: info@cybecube.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cybecube.academy.registry.model

import javax.persistence.Entity


/**
 * 
 * @param id 
 * @param address Logical address of the assistant
 * @param va_host Physical server/host/ip address
 * @param va_node Logical address linked to host
 * @param va_ports Linked list of ports, as string
 * @param cloud_address Location info linked to cloud services (AWS,Azure,Google)
 */
@Entity
data class Location (
    val id: kotlin.Long? = null,
    /* Logical address of the assistant */
    val address: kotlin.String? = null,
    /* Physical server/host/ip address */
    val va_host: kotlin.String? = null,
    /* Logical address linked to host */
    val va_node: kotlin.String? = null,
    /* Linked list of ports, as string */
    val va_ports: kotlin.String? = null,
    /* Location info linked to cloud services (AWS,Azure,Google) */
    val cloud_address: kotlin.String? = null
) {

}

