/**
* CybeCube Gate
* This is the api for the cybecube gate.  The cybecube gate is an way to access programmatically cybecube's virtual assistents.
*
* OpenAPI spec version: 1.0.0
* Contact: info@cybecube.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cybecube.academy.registry.model


/**
 * 
 * @param id 
 * @param name 
 * @param url 
 * @param status 
 */
data class Resource (
    val id: kotlin.Long? = null,
    val name: kotlin.String? = null,
    val url: kotlin.String? = null,
    /*  */
    val status: Resource.Status? = null
) {

    /**
    * 
    * Values: available,learning,working
    */
    enum class Status(val value: kotlin.Any){
    
        available("available"),
    
        learning("learning"),
    
        working("working");
    
    }

}

